version: '3'
# 立てるコンテナの指定 ここでは,appとdb
services:
  app:
    # docker配下のパス指定
    build: ./docker
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    depends_on:
      - db
  db:
    # M1にはこのplatform必要
    platform: linux/x86_64
    image: mysql:5.7
    container_name: laravel_db
    ports:
      - 3306:3306
    # 環境変数
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: strongrootpassword
      